fix: remove gas overrides
valory-xyz/optimus pull request #16
Opened 2024-09-25 16:14 UTC by Divya-Solulab

2024-09-25 17:47 UTC, gauravlochab approved these changes

2024-09-26 10:33 UTC, Adamantios requested changes
You should also remove those:

https://github.com/valory-xyz/optimus/blob/9c6c3f94158702ab479c449787147edca17d0e60/packages/valory/skills/optimus_abci/skill.yaml#L153-L156

2024-09-26 10:39 UTC, Divya-Solulab commented
> You should also remove those:
> 
> https://github.com/valory-xyz/optimus/blob/9c6c3f94158702ab479c449787147edca17d0e60/packages/valory/skills/optimus_abci/skill.yaml#L153-L156



> You should also remove those:
> 
> https://github.com/valory-xyz/optimus/blob/9c6c3f94158702ab479c449787147edca17d0e60/packages/valory/skills/optimus_abci/skill.yaml#L153-L156

resolved in the latest commit

2024-09-26 14:48 UTC, Divya-Solulab commented
> There are remaining instances of `manual_gas_limit` in configurations and models. Looks like it is not necessary anymore.

Resolved in this commit 195cf650e20bde46c645d166755ea41cd422f0ae

2024-09-26 15:09 UTC, dagacha approved these changes

2024-09-26 16:06 UTC, merged